import './globals.css'
import { Inter } from 'next/font/google'
import Provider from './providers'
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <body className={inter.className}>
      <Theme>
        <Provider>
        {children}
        </Provider>
      </Theme> 
        </body>
    </html>
  )
}